# Generated by Django 5.2.17 on 2026-09-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_staff', True), ('is_superuser', True), ('role', 'super_admin')), models.Q(('is_superuser', False), models.Q(('role', 'super_admin'), _negated=True)), _connector='OR'), name='accounts_superuser_role_consistent'),
        ),
    ]
