# Generated by Django 5.2.17 on 2026-09-22 07:16

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def retire_guardian_logins(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.using(schema_editor.connection.alias).filter(role='guardian').update(
        role='student', is_active=False, is_staff=False, is_superuser=False,
        password=make_password(None),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accounts_superuser_role_consistent'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('students', '0002_guardian_contacts_and_student_portal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_valid_role',
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('headteacher', 'Headteacher'), ('teacher', 'Teacher'), ('bursar', 'Bursar / Finance'), ('student', 'Student portal')], default='student', max_length=20),
        ),
        migrations.RunPython(retire_guardian_logins),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['super_admin', 'school_admin', 'headteacher', 'teacher', 'bursar', 'student'])), name='accounts_user_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'student'), _negated=True), models.Q(('is_staff', False), ('is_superuser', False)), _connector='OR'), name='accounts_student_not_staff'),
        ),
    ]
