# Generated by Django 5.2.17 on 2026-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_portal_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_valid_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('headteacher', 'Headteacher'), ('teacher', 'Teacher'), ('bursar', 'Bursar / Finance'), ('guardian', 'Guardian'), ('student', 'Student portal')], default='guardian', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['super_admin', 'school_admin', 'headteacher', 'teacher', 'bursar', 'guardian', 'student'])), name='accounts_user_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'guardian'), _negated=True), models.Q(('is_staff', False), ('is_superuser', False)), _connector='OR'), name='accounts_guardian_not_staff'),
        ),
    ]
