# Generated by Django 5.2.17 on 2026-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_independent_guardian_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_started', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
