# Generated by Django 5.2.17 on 2026-09-22 10:36

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_terms_order_by_start_date'),
        ('students', '0002_guardian_contacts_and_student_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptNumber',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='schools.school')),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FeeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(max_length=3)),
                ('due_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_charges', to='students.enrollment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ChargeCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='finance.feecharge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='General', help_text='For example, General, Day or Boarding.', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='schools.academicclass')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='schools.stream')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='schools.term')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-term__academic_year__start_date', 'term__start_date', 'academic_class__sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='feecharge',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='finance.feestructure'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer / deposit'), ('mobile', 'Mobile money'), ('other', 'Other')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('receipt', models.JSONField(default=dict)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.feecharge')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=500)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.payment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_structure_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(models.F('term'), models.F('academic_class'), models.F('stream'), django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('category'), condition=models.Q(('stream__isnull', False)), name='finance_structure_stream_unique'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(models.F('term'), models.F('academic_class'), django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('category'), condition=models.Q(('stream__isnull', True)), name='finance_structure_class_unique'),
        ),
        migrations.AddConstraint(
            model_name='feecharge',
            constraint=models.UniqueConstraint(fields=('enrollment', 'structure'), name='finance_charge_assignment_unique'),
        ),
        migrations.AddConstraint(
            model_name='feecharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_charge_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('new_balance', django.db.models.expressions.CombinedExpression(models.F('previous_balance'), '-', models.F('amount')))), name='finance_payment_balance_math'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('reference'), condition=models.Q(('reference', ''), _negated=True), name='finance_payment_reference_unique'),
        ),
    ]
