# Generated by Django 5.2.17 on 2026-09-22 10:38

import django.db.models.expressions
import django.db.models.functions.math
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_fee_ledger_and_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='finance_payment_balance_math',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('new_balance', django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('previous_balance'), '-', models.F('amount')), precision=2))), name='finance_payment_balance_math'),
        ),
    ]
