# Generated by Django 5.2.17 on 2026-09-22 07:25

import apps.academics.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_terms_order_by_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='schools.section')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('section__sort_order', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.CharField(default=apps.academics.models.teacher_identifier, editable=False, max_length=20, unique=True)),
                ('phone', models.CharField(max_length=40)),
                ('date_joined', models.DateField(default=django.utils.timezone.localdate)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('leave', 'On leave'), ('left', 'Left school')], default='active', max_length=10)),
                ('specialization', models.CharField(blank=True, max_length=160)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.academicyear')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.section')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.stream')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.term')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_assignments', to='academics.teacher')),
            ],
            options={
                'ordering': ('-academic_year__start_date', 'academic_class__sort_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.academicyear')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.section')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='academics.teacher')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='schools.term')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-academic_year__start_date', 'academic_class__sort_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('section'), name='academics_subject_code_unique', violation_error_message='This subject code is already used in the section.'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('section'), name='academics_subject_name_unique', violation_error_message='This subject name is already used in the section.'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('employment_status__in', ['active', 'leave', 'left'])), name='academics_teacher_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='classteacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('stream__isnull', True), ('term__isnull', True)), fields=('academic_year', 'academic_class'), name='academics_class_teacher_scope_11', violation_error_message='An active assignment already exists for this scope.'),
        ),
        migrations.AddConstraint(
            model_name='classteacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('stream__isnull', False), ('term__isnull', True)), fields=('academic_year', 'academic_class', 'stream'), name='academics_class_teacher_scope_10', violation_error_message='An active assignment already exists for this scope.'),
        ),
        migrations.AddConstraint(
            model_name='classteacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('stream__isnull', True), ('term__isnull', False)), fields=('academic_year', 'academic_class', 'term'), name='academics_class_teacher_scope_01', violation_error_message='An active assignment already exists for this scope.'),
        ),
        migrations.AddConstraint(
            model_name='classteacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('stream__isnull', False), ('term__isnull', False)), fields=('academic_year', 'academic_class', 'term', 'stream'), name='academics_class_teacher_scope_00', violation_error_message='An active assignment already exists for this scope.'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('stream__isnull', True), ('term__isnull', True)), fields=('academic_year', 'academic_class', 'subject'), name='academics_teaching_scope_11', violation_error_message='An active assignment already exists for this scope.'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('stream__isnull', False), ('term__isnull', True)), fields=('academic_year', 'academic_class', 'subject', 'stream'), name='academics_teaching_scope_10', violation_error_message='An active assignment already exists for this scope.'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('stream__isnull', True), ('term__isnull', False)), fields=('academic_year', 'academic_class', 'subject', 'term'), name='academics_teaching_scope_01', violation_error_message='An active assignment already exists for this scope.'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('stream__isnull', False), ('term__isnull', False)), fields=('academic_year', 'academic_class', 'subject', 'term', 'stream'), name='academics_teaching_scope_00', violation_error_message='An active assignment already exists for this scope.'),
        ),
    ]
