# Generated by Django 5.2.17 on 2026-09-22 07:44

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_assessments_and_marks'),
        ('schools', '0003_terms_order_by_start_date'),
        ('students', '0002_guardian_contacts_and_student_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('numeric', 'Numeric grades'), ('descriptive', 'Descriptive learning levels')], default='numeric', max_length=12)),
                ('aggregate_mode', models.CharField(choices=[('none', 'No aggregate'), ('all', 'All graded subjects'), ('best', 'Best N subjects, including required subjects'), ('selected', 'Required subject combination only')], default='none', max_length=10)),
                ('best_n', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('section__sort_order', 'name', 'pk'),
            },
        ),
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='DivisionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=60)),
                ('minimum', models.PositiveIntegerField()),
                ('maximum', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scheme__name', 'minimum', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='GradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=60)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scheme__name', 'sort_order', '-minimum', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='mark',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descriptive_marks', to='academics.graderule'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level__isnull', True), ('score__isnull', False)), models.Q(('level__isnull', False), ('score__isnull', True)), _connector='OR'), name='academics_mark_value_exclusive'),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='required_subjects',
            field=models.ManyToManyField(blank=True, related_name='required_in_schemes', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_schemes', to='schools.section'),
        ),
        migrations.AddField(
            model_name='gradingscheme',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graderule',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='academics.gradingscheme'),
        ),
        migrations.AddField(
            model_name='divisionrule',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='academics.gradingscheme'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='grading_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.gradingscheme'),
        ),
        migrations.AddConstraint(
            model_name='gradingscheme',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('section'), name='academics_grading_scheme_name'),
        ),
        migrations.AddConstraint(
            model_name='graderule',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), models.F('scheme'), name='academics_grade_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='divisionrule',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), models.F('scheme'), name='academics_division_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='divisionrule',
            constraint=models.CheckConstraint(condition=models.Q(('maximum__gte', models.F('minimum'))), name='academics_division_range'),
        ),
    ]
