# Generated by Django 5.2.17 on 2026-09-23 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_configurable_grading'),
        ('students', '0006_remove_student_students_valid_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'In progress'), ('submitted', 'Awaiting review'), ('approved', 'Approved'), ('returned', 'Returned for correction')], default='draft', max_length=12)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='mark',
            name='academics_mark_value_exclusive',
        ),
        migrations.AddField(
            model_name='assessment',
            name='requires_mark_review',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='requires_mark_review',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='mark',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_absent', True), ('level__isnull', True), ('score__isnull', True)), models.Q(('is_absent', False), models.Q(models.Q(('level__isnull', True), ('score__isnull', False)), models.Q(('level__isnull', False), ('score__isnull', True)), _connector='OR')), _connector='OR'), name='academics_mark_value_exclusive'),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_submissions', to='academics.assessment'),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_submissions', to='academics.teachingassignment'),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_mark_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_mark_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='marksubmission',
            constraint=models.UniqueConstraint(fields=('assessment', 'assignment'), name='academics_submission_unique'),
        ),
        migrations.AddConstraint(
            model_name='marksubmission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'approved', 'returned'])), name='academics_submission_status'),
        ),
    ]
