# Generated by Django 5.2.17 on 2026-09-24 17:59

from django.db import migrations, models


def disable_existing_review(apps, schema_editor):
    apps.get_model('academics', 'Assessment').objects.using(schema_editor.connection.alias).update(requires_mark_review=False)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_marksubmission_and_more'),
    ]

    operations = [
        migrations.RunPython(disable_existing_review, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='assessment',
            name='requires_mark_review',
            field=models.BooleanField(default=False, help_text='Enable submission and approval of subject marks before closing the assessment.', verbose_name='Require marks review'),
        ),
    ]
