# Generated by Django 5.2.17 on 2026-09-27 06:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def configure_end_term(apps, schema_editor):
    alias = schema_editor.connection.alias
    Type = apps.get_model('academics', 'AssessmentType')
    Assessment = apps.get_model('academics', 'Assessment')
    ExamSet = apps.get_model('academics', 'ExamSet')
    for kind in Type.objects.using(alias).all():
        normalized = ''.join(c for c in kind.name.casefold() if c.isalnum())
        if normalized not in ('endterm', 'endofterm'):
            continue
        Type.objects.using(alias).filter(pk=kind.pk).update(two_exam_sets=True)
        for assessment in Assessment.objects.using(alias).filter(assessment_type_id=kind.pk, marks__isnull=True, reports__isnull=True, mark_submissions__isnull=True).exclude(status='closed').exclude(grading_scheme__mode='descriptive').distinct():
            Assessment.objects.using(alias).filter(pk=assessment.pk).update(two_exam_sets=True)
            for number in (1, 2):
                ExamSet.objects.using(alias).create(assessment_id=assessment.pk, number=number)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_assessment_requires_mark_review'),
        ('students', '0008_remove_student_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'Set One'), (2, 'Set Two')])),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='mark',
            name='academics_mark_unique',
        ),
        migrations.RemoveConstraint(
            model_name='marksubmission',
            name='academics_submission_unique',
        ),
        migrations.AddField(
            model_name='assessment',
            name='set_one_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text="Set One percentage. Set Two receives the remaining percentage; both use this assessment's maximum score.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='assessment',
            name='two_exam_sets',
            field=models.BooleanField(default=False, verbose_name='Use Set One and Set Two'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='two_exam_sets',
            field=models.BooleanField(default=False, help_text='Create Set One and Set Two for new assessments of this type.'),
        ),
        migrations.AddField(
            model_name='examset',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sets', to='academics.assessment'),
        ),
        migrations.AddField(
            model_name='examset',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examset',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mark',
            name='exam_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='academics.examset'),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='exam_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='academics.examset'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_set__isnull', True)), fields=('assessment', 'enrollment', 'subject'), name='academics_mark_unique'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_set__isnull', False)), fields=('assessment', 'enrollment', 'subject', 'exam_set'), name='academics_mark_set_unique'),
        ),
        migrations.AddConstraint(
            model_name='marksubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_set__isnull', True)), fields=('assessment', 'assignment'), name='academics_submission_unique'),
        ),
        migrations.AddConstraint(
            model_name='marksubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_set__isnull', False)), fields=('assessment', 'assignment', 'exam_set'), name='academics_submission_set_unique'),
        ),
        migrations.AddConstraint(
            model_name='examset',
            constraint=models.UniqueConstraint(fields=('assessment', 'number'), name='academics_exam_set_unique'),
        ),
        migrations.AddConstraint(
            model_name='examset',
            constraint=models.CheckConstraint(condition=models.Q(('number__in', [1, 2])), name='academics_exam_set_number'),
        ),
        migrations.RunPython(configure_end_term, migrations.RunPython.noop),
    ]
