# Generated by Django 5.2.17 on 2026-09-27 07:20

from django.db import migrations, models


def enable_midterm_screen_reports(apps, schema_editor):
    types = apps.get_model('academics', 'AssessmentType').objects.using(schema_editor.connection.alias)
    for kind in types.all():
        normalized = ''.join(character for character in kind.name.casefold() if character.isalnum())
        if normalized.endswith('midterm'):
            types.filter(pk=kind.pk).update(screen_only_report=True)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_examset_remove_mark_academics_mark_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='screen_only_report',
            field=models.BooleanField(default=False, help_text='Show reports online without print or PDF downloads. Use for Mid-Term assessments.'),
        ),
        migrations.RunPython(enable_midterm_screen_reports, migrations.RunPython.noop),
    ]
