# Generated by Django 5.2.17 on 2026-10-01 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_assessmenttype_screen_only_report'),
        ('schools', '0004_headteacher_comment_thresholds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessment',
            name='academics_assessment_stream_unique',
        ),
        migrations.RemoveConstraint(
            model_name='assessment',
            name='academics_assessment_class_unique',
        ),
        migrations.AddField(
            model_name='assessment',
            name='report_group',
            field=models.CharField(choices=[('main', 'Main School'), ('islamic', 'Islamic Studies')], default='main', help_text='Islamic Studies includes only students registered with religion Islam and Islamic subjects.', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='report_group',
            field=models.CharField(choices=[('main', 'Main School'), ('islamic', 'Islamic Studies')], default='main', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', False)), fields=('assessment_type', 'term', 'academic_class', 'stream', 'report_group'), name='academics_assessment_stream_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', True)), fields=('assessment_type', 'term', 'academic_class', 'report_group'), name='academics_assessment_class_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('report_group__in', ['main', 'islamic'])), name='academics_assessment_group'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('report_group__in', ['main', 'islamic'])), name='academics_subject_group'),
        ),
    ]
