# Generated by Django 5.2.17 on 2026-09-21 17:28

import apps.students.photos
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_alter_academicclass_schools_class_name_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNumber',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='schools.school')),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardians', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, storage=apps.students.photos.PrivatePhotoStorage(), upload_to=apps.students.photos.photo_path)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unspecified', 'Not specified')], default='unspecified', max_length=12)),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField(default=django.utils.timezone.localdate)),
                ('admission_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('repeating', 'Repeating'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=12)),
                ('address', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('completed', 'Completed'), ('promoted', 'Promoted'), ('repeating', 'Repeating'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='current', max_length=12)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.academicclass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.academicyear')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.section')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schools.stream')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ('-academic_year__start_date', '-enrollment_date', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(max_length=60)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_links', to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_links', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_active', '-is_primary', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('date_of_birth__lte', models.F('admission_date'))), name='students_birth_before_admission'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'promoted', 'repeating', 'transferred', 'withdrawn', 'graduated', 'inactive'])), name='students_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['female', 'male', 'other', 'unspecified'])), name='students_valid_gender'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('student_id', ''), _negated=True), name='students_id_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('admission_number'), models.F('school'), condition=models.Q(('admission_number', ''), _negated=True), name='students_admission_unique', violation_error_message='This admission number is already in use.'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'current')), fields=('student', 'academic_year'), name='students_current_enrollment_unique', violation_error_message="Close this student's current enrollment for this year first."),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['current', 'completed', 'promoted', 'repeating', 'transferred', 'withdrawn', 'graduated'])), name='students_enrollment_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completion_date__isnull', True), ('status', 'current')), models.Q(models.Q(('status', 'current'), _negated=True), ('completion_date__isnull', False)), _connector='OR'), name='students_enrollment_completion'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('completion_date__isnull', True), ('completion_date__gte', models.F('enrollment_date')), _connector='OR'), name='students_enrollment_dates'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='students_guardian_link_unique', violation_error_message='This guardian is already linked. Edit or reactivate the existing link.'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('student',), name='students_one_primary_guardian', violation_error_message='This student already has a primary guardian. Unmark that guardian first.'),
        ),
    ]
