# Generated by Django 5.2.17 on 2026-09-22 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_guardian_contacts(apps, schema_editor):
    Guardian = apps.get_model('students', 'Guardian')
    for guardian in Guardian.objects.using(schema_editor.connection.alias).select_related('user').all():
        user = guardian.user
        guardian.first_name = user.first_name or user.username
        guardian.last_name = user.last_name or 'Guardian'
        guardian.email = user.email
        guardian.save(using=schema_editor.connection.alias, update_fields=['first_name', 'last_name', 'email'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ('last_name', 'first_name', 'pk')},
        ),
        migrations.AddField(
            model_name='guardian',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='guardian',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='guardian',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.RunPython(preserve_guardian_contacts),
        migrations.RemoveField(model_name='guardian', name='user'),
        migrations.AddField(
            model_name='student',
            name='portal_user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
