# Generated by Django 5.2.17 on 2026-09-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_independent_guardian_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='nin',
            field=models.CharField(blank=True, max_length=50, verbose_name='National Identification Number (NIN)'),
        ),
    ]
