# Generated by Django 5.2.17 on 2026-09-25 13:29

from django.db import migrations, models


def normalize_religion(apps, schema_editor):
    students = apps.get_model('students', 'Student').objects.using(schema_editor.connection.alias)
    aliases = {'moslem': 'Moslem', 'muslim': 'Moslem', 'islam': 'Moslem',
               'christian': 'Christian', 'christianity': 'Christian', 'other': 'Other', '': ''}
    for value in students.order_by().values_list('religion', flat=True).distinct():
        normalized = aliases.get(value.strip().lower(), 'Other')
        if value != normalized:
            students.filter(religion=value).update(religion=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_students_valid_gender_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_religion, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Moslem', 'Moslem'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=100),
        ),
    ]
