# Generated by Django 5.2.17 on 2026-09-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact_phone',
        ),
    ]
