# Generated by Django 5.2.17 on 2026-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Moslem', 'Islam'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=100),
        ),
    ]
