# Generated by Django 5.2.17 on 2026-09-22 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_terms_order_by_start_date'),
        ('students', '0003_independent_guardian_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateField()),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=12)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_batches', to='schools.academicclass')),
                ('destination_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_batches', to='schools.stream')),
                ('destination_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_batches', to='schools.academicyear')),
                ('source_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_batches', to='schools.academicclass')),
                ('source_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_batches', to='schools.stream')),
                ('source_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_batches', to='schools.academicyear')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PromotionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('promoted', 'Promote'), ('repeating', 'Repeat'), ('transferred', 'Transfer out'), ('withdrawn', 'Withdraw'), ('graduated', 'Graduate')], max_length=12)),
                ('selected', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='promotions.promotionbatch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_decisions', to='students.enrollment')),
                ('new_enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_origin', to='students.enrollment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('enrollment__student__last_name', 'enrollment__student__first_name', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='promotionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'confirmed'])), name='promotions_batch_status'),
        ),
        migrations.AddConstraint(
            model_name='promotionbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('status', 'draft')), models.Q(('confirmed_at__isnull', False), ('status', 'confirmed')), _connector='OR'), name='promotions_confirmation_time'),
        ),
        migrations.AddConstraint(
            model_name='promotiondecision',
            constraint=models.UniqueConstraint(fields=('batch', 'enrollment'), name='promotions_decision_unique'),
        ),
        migrations.AddConstraint(
            model_name='promotiondecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['promoted', 'repeating', 'transferred', 'withdrawn', 'graduated'])), name='promotions_decision_valid'),
        ),
    ]
