# Generated by Django 5.2.17 on 2026-09-25 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_promotion_batches_and_history'),
        ('students', '0008_remove_student_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotiondecision',
            name='promotions_decision_valid',
        ),
        migrations.AlterField(
            model_name='promotiondecision',
            name='decision',
            field=models.CharField(choices=[('promoted', 'Promoted'), ('probation', 'Promoted On Probation'), ('repeating', 'Try Again'), ('transferred', 'Transfer out'), ('withdrawn', 'Withdraw'), ('graduated', 'Graduate')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='promotiondecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['promoted', 'probation', 'repeating', 'transferred', 'withdrawn', 'graduated'])), name='promotions_decision_valid'),
        ),
    ]
