# Generated by Django 5.2.17 on 2026-09-21 17:09

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='academicclass',
            name='schools_class_name_unique',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('section'), name='schools_class_name_unique', violation_error_message='A class with this name already exists in this section.'),
        ),
        migrations.AlterConstraint(
            model_name='academicyear',
            name='schools_year_name_unique',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('school'), name='schools_year_name_unique', violation_error_message='An academic year with this name already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='section',
            name='schools_section_name_unique',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('school'), name='schools_section_name_unique', violation_error_message='A section with this name already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='stream',
            name='schools_stream_name_unique',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('academic_class'), name='schools_stream_name_unique', violation_error_message='A stream with this name already exists in this class.'),
        ),
        migrations.AlterConstraint(
            model_name='term',
            name='schools_term_name_unique',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('academic_year'), name='schools_term_name_unique', violation_error_message='A term with this name already exists in this academic year.'),
        ),
        migrations.AlterConstraint(
            model_name='term',
            name='schools_term_sequence_unique',
            constraint=models.UniqueConstraint(fields=('academic_year', 'sequence'), name='schools_term_sequence_unique', violation_error_message='This term number is already used in this academic year.'),
        ),
    ]
