# Generated by Django 5.2.17 on 2026-09-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_academicclass_schools_class_name_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ('-academic_year__start_date', 'start_date', 'pk')},
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='schools_term_sequence_unique',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='schools_term_sequence_positive',
        ),
        migrations.RemoveField(
            model_name='term',
            name='sequence',
        ),
    ]
