# Generated by Django 5.2.17 on 2026-09-28 09:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_terms_order_by_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='headteacher_moderate_min',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Headteacher moderate minimum (%)'),
        ),
        migrations.AddField(
            model_name='school',
            name='headteacher_outstanding_min',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Headteacher outstanding minimum (%)'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.CheckConstraint(condition=models.Q(('headteacher_moderate_min__gte', 0), ('headteacher_outstanding_min__gt', models.F('headteacher_moderate_min')), ('headteacher_outstanding_min__lte', 100)), name='schools_headteacher_comment_thresholds'),
        ),
    ]
