# Generated by Django 5.2.17 on 2026-09-22 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_configurable_grading'),
        ('students', '0002_guardian_contacts_and_student_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('correction_reason', models.TextField(blank=True, max_length=2000)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('teacher_comment', models.TextField(blank=True, max_length=2000)),
                ('headteacher_comment', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Awaiting class-teacher comment'), ('review', 'Awaiting headteacher review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='academics.assessment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='students.enrollment')),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='reports.studentreport')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assessment__date', 'enrollment__student__last_name', 'enrollment__student__first_name', '-version'),
                'constraints': [models.UniqueConstraint(fields=('assessment', 'enrollment', 'version'), name='reports_version_unique'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('assessment', 'enrollment'), name='reports_current_unique'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'review', 'approved', 'published'])), name='reports_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='reports_publication_time')],
            },
        ),
    ]
